apiVersion: v1
kind: Service
metadata:
  name: {{ include "fddb-exporter.fullname" . }}
  labels:
    app: {{ include "fddb-exporter.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ include "fddb-exporter.name" . }}
