{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fddb-exporter.fullname" . }}
  labels:
    app: {{ include "fddb-exporter.name" . }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ include "fddb-exporter.name" . }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    path: /metrics
{{- end }}
